[package]
name = "gaveldrop-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Command-line facade for gaveldrop."

[[bin]]
name = "gaveldrop"
path = "src/main.rs"

[dependencies]
gaveldrop = { path = "../gaveldrop", version = "0.1.13" }
anstream.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
