[package]
name = "gaveldrop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "YAML-driven test engine: one case is one file."

[dependencies]
gaveldrop-fake = { path = "../gaveldrop-fake", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
schemars.workspace = true
thiserror.workspace = true
anstream.workspace = true
anstyle.workspace = true
glob.workspace = true
tempfile.workspace = true

[dev-dependencies]
assert_cmd.workspace = true

[lints]
workspace = true
